"""Create merchant onboarding tables

Revision ID: 22ecd7c9e654
Revises: 
Create Date: 2025-09-30 11:26:51.289479

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "22ecd7c9e654"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "merchant_application",
        sa.Column("business_name", sa.String(length=200), nullable=False, comment="企业名称"),
        sa.Column(
            "unified_social_credit",
            sa.String(length=18),
            nullable=False,
            comment="统一社会信用代码（营业执照号）",
        ),
        sa.Column("legal_person_name", sa.String(length=100), nullable=False, comment="法人姓名"),
        sa.Column(
            "legal_person_id_number",
            sa.String(length=18),
            nullable=False,
            comment="法人身份证号（敏感信息，暂用明文，后续加密）",
        ),
        sa.Column("contact_name", sa.String(length=100), nullable=False, comment="联系人姓名"),
        sa.Column(
            "contact_phone",
            sa.String(length=20),
            nullable=False,
            comment="联系电话（敏感信息，暂用明文，后续加密）",
        ),
        sa.Column("contact_email", sa.String(length=255), nullable=False, comment="联系邮箱"),
        sa.Column(
            "business_categories",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            comment='经营类目（JSONB 数组，如 ["食品", "服装"]）',
        ),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "PENDING",
                "UNDER_REVIEW",
                "REQUIRE_SUPPLEMENT",
                "APPROVED",
                "REJECTED",
                name="applicationstatus",
            ),
            nullable=False,
            comment="申请状态",
        ),
        sa.Column(
            "submitted_at", sa.DateTime(), nullable=True, comment="提交时间（从草稿状态提交时记录）"
        ),
        sa.Column("id", sa.UUID(), nullable=False, comment="主键 UUID"),
        sa.Column("created_at", sa.DateTime(), nullable=False, comment="创建时间"),
        sa.Column("updated_at", sa.DateTime(), nullable=False, comment="更新时间"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("unified_social_credit"),
    )
    op.create_index(
        "idx_merchant_application_business_name",
        "merchant_application",
        ["business_name"],
        unique=False,
    )
    op.create_index(
        "idx_merchant_application_credit_code",
        "merchant_application",
        ["unified_social_credit"],
        unique=False,
    )
    op.create_index(
        "idx_merchant_application_status",
        "merchant_application",
        ["status", "created_at"],
        unique=False,
    )
    op.create_index(
        "idx_merchant_application_submitted_at",
        "merchant_application",
        ["submitted_at"],
        unique=False,
        postgresql_using="btree",
    )
    op.create_table(
        "audit_record",
        sa.Column("application_id", sa.UUID(), nullable=False, comment="关联商家申请 ID"),
        sa.Column(
            "auditor_id",
            sa.UUID(),
            nullable=False,
            comment="审核员用户 ID（关联用户表，本 feature 未实现）",
        ),
        sa.Column(
            "auditor_name",
            sa.String(length=100),
            nullable=False,
            comment="审核员姓名（冗余存储，便于历史查询）",
        ),
        sa.Column(
            "action",
            sa.Enum("START_REVIEW", "APPROVE", "REJECT", "REQUEST_SUPPLEMENT", name="auditaction"),
            nullable=False,
            comment="审核动作",
        ),
        sa.Column(
            "result",
            sa.Enum(
                "APPROVED", "REJECTED", "PENDING_SUPPLEMENT", "IN_PROGRESS", name="auditresult"
            ),
            nullable=False,
            comment="审核结果",
        ),
        sa.Column("comment", sa.Text(), nullable=True, comment="审核意见/备注"),
        sa.Column("id", sa.UUID(), nullable=False, comment="主键 UUID"),
        sa.Column("created_at", sa.DateTime(), nullable=False, comment="创建时间"),
        sa.Column("updated_at", sa.DateTime(), nullable=False, comment="更新时间"),
        sa.ForeignKeyConstraint(
            ["application_id"], ["merchant_application.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_audit_record_application_id",
        "audit_record",
        ["application_id", "created_at"],
        unique=False,
        postgresql_using="btree",
    )
    op.create_index("idx_audit_record_auditor_id", "audit_record", ["auditor_id"], unique=False)
    op.create_index("idx_audit_record_created_at", "audit_record", ["created_at"], unique=False)
    op.create_table(
        "merchant_account",
        sa.Column(
            "merchant_id",
            sa.String(length=20),
            nullable=False,
            comment="商家编号（如 M20250930001）",
        ),
        sa.Column(
            "username",
            sa.String(length=50),
            nullable=False,
            comment="登录用户名（默认使用联系人电话或邮箱）",
        ),
        sa.Column(
            "password_hash",
            sa.String(length=255),
            nullable=False,
            comment="密码哈希（使用 bcrypt）",
        ),
        sa.Column(
            "level",
            sa.Enum("NORMAL", "VIP", "DIAMOND", name="merchantlevel"),
            nullable=False,
            comment="商家等级",
        ),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "FROZEN", "CLOSED", name="merchantstatus"),
            nullable=False,
            comment="账户状态",
        ),
        sa.Column(
            "application_id",
            sa.UUID(),
            nullable=False,
            comment="关联的入驻申请 ID（一个申请对应一个账户）",
        ),
        sa.Column("id", sa.UUID(), nullable=False, comment="主键 UUID"),
        sa.Column("created_at", sa.DateTime(), nullable=False, comment="创建时间"),
        sa.Column("updated_at", sa.DateTime(), nullable=False, comment="更新时间"),
        sa.ForeignKeyConstraint(
            ["application_id"], ["merchant_application.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("application_id"),
        sa.UniqueConstraint("merchant_id"),
        sa.UniqueConstraint("username"),
    )
    op.create_index(
        "idx_merchant_account_application_id", "merchant_account", ["application_id"], unique=False
    )
    op.create_index(
        "idx_merchant_account_level_status", "merchant_account", ["level", "status"], unique=False
    )
    op.create_index(
        "idx_merchant_account_merchant_id", "merchant_account", ["merchant_id"], unique=True
    )
    op.create_index("idx_merchant_account_username", "merchant_account", ["username"], unique=True)
    op.create_table(
        "contract_file",
        sa.Column("merchant_id", sa.String(length=20), nullable=False, comment="关联商家账户 ID"),
        sa.Column(
            "file_path",
            sa.String(length=500),
            nullable=False,
            comment="文件存储路径（相对路径或 S3 Key）",
        ),
        sa.Column("file_size", sa.BigInteger(), nullable=False, comment="文件大小（字节）"),
        sa.Column(
            "file_type",
            sa.String(length=50),
            nullable=False,
            comment="文件类型（MIME type，如 image/jpeg）",
        ),
        sa.Column(
            "upload_by",
            sa.String(length=100),
            nullable=False,
            comment="上传人（商家用户名或平台管理员）",
        ),
        sa.Column("uploaded_at", sa.DateTime(), nullable=False, comment="上传时间"),
        sa.Column("id", sa.UUID(), nullable=False, comment="主键 UUID"),
        sa.Column("created_at", sa.DateTime(), nullable=False, comment="创建时间"),
        sa.Column("updated_at", sa.DateTime(), nullable=False, comment="更新时间"),
        sa.CheckConstraint(
            "file_size > 0 AND file_size <= 10485760", name="chk_contract_file_size"
        ),
        sa.ForeignKeyConstraint(
            ["merchant_id"], ["merchant_account.merchant_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_contract_file_merchant_id",
        "contract_file",
        ["merchant_id", "uploaded_at"],
        unique=False,
        postgresql_using="btree",
    )
    op.create_index("idx_contract_file_uploaded_at", "contract_file", ["uploaded_at"], unique=False)
    op.create_table(
        "qualification_file",
        sa.Column("application_id", sa.UUID(), nullable=False, comment="关联商家申请 ID"),
        sa.Column(
            "merchant_id",
            sa.String(length=20),
            nullable=True,
            comment="关联商家账户 ID（审核通过后关联）",
        ),
        sa.Column(
            "file_type",
            sa.Enum(
                "BUSINESS_LICENSE",
                "ID_CARD_FRONT",
                "ID_CARD_BACK",
                "OTHER",
                name="qualificationfiletype",
            ),
            nullable=False,
            comment="文件类型",
        ),
        sa.Column("file_path", sa.String(length=500), nullable=False, comment="文件存储路径"),
        sa.Column("file_size", sa.BigInteger(), nullable=False, comment="文件大小（字节）"),
        sa.Column(
            "audit_status",
            sa.Enum("PENDING", "APPROVED", "REJECTED", name="fileauditstatus"),
            nullable=False,
            comment="审核状态",
        ),
        sa.Column("uploaded_at", sa.DateTime(), nullable=False, comment="上传时间"),
        sa.Column("id", sa.UUID(), nullable=False, comment="主键 UUID"),
        sa.Column("created_at", sa.DateTime(), nullable=False, comment="创建时间"),
        sa.Column("updated_at", sa.DateTime(), nullable=False, comment="更新时间"),
        sa.CheckConstraint(
            "file_size > 0 AND file_size <= 10485760", name="chk_qualification_file_size"
        ),
        sa.ForeignKeyConstraint(
            ["application_id"], ["merchant_application.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["merchant_id"], ["merchant_account.merchant_id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_qualification_file_application_id",
        "qualification_file",
        ["application_id", "file_type"],
        unique=False,
    )
    op.create_index(
        "idx_qualification_file_audit_status", "qualification_file", ["audit_status"], unique=False
    )
    op.create_index(
        "idx_qualification_file_merchant_id", "qualification_file", ["merchant_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_qualification_file_merchant_id", table_name="qualification_file")
    op.drop_index("idx_qualification_file_audit_status", table_name="qualification_file")
    op.drop_index("idx_qualification_file_application_id", table_name="qualification_file")
    op.drop_table("qualification_file")
    op.drop_index("idx_contract_file_uploaded_at", table_name="contract_file")
    op.drop_index(
        "idx_contract_file_merchant_id", table_name="contract_file", postgresql_using="btree"
    )
    op.drop_table("contract_file")
    op.drop_index("idx_merchant_account_username", table_name="merchant_account")
    op.drop_index("idx_merchant_account_merchant_id", table_name="merchant_account")
    op.drop_index("idx_merchant_account_level_status", table_name="merchant_account")
    op.drop_index("idx_merchant_account_application_id", table_name="merchant_account")
    op.drop_table("merchant_account")
    op.drop_index("idx_audit_record_created_at", table_name="audit_record")
    op.drop_index("idx_audit_record_auditor_id", table_name="audit_record")
    op.drop_index(
        "idx_audit_record_application_id", table_name="audit_record", postgresql_using="btree"
    )
    op.drop_table("audit_record")
    op.drop_index(
        "idx_merchant_application_submitted_at",
        table_name="merchant_application",
        postgresql_using="btree",
    )
    op.drop_index("idx_merchant_application_status", table_name="merchant_application")
    op.drop_index("idx_merchant_application_credit_code", table_name="merchant_application")
    op.drop_index("idx_merchant_application_business_name", table_name="merchant_application")
    op.drop_table("merchant_application")
    # ### end Alembic commands ###
