"""Add admin_user table

Revision ID: 726b4b728934
Revises: 22ecd7c9e654
Create Date: 2025-09-30 12:51:55.014997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "726b4b728934"
down_revision: Union[str, None] = "22ecd7c9e654"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admin_user",
        sa.Column("username", sa.String(length=50), nullable=False, comment="登录用户名"),
        sa.Column(
            "password_hash", sa.String(length=255), nullable=False, comment="密码哈希（使用 bcrypt）"
        ),
        sa.Column("name", sa.String(length=100), nullable=False, comment="管理员姓名"),
        sa.Column("email", sa.String(length=255), nullable=True, comment="邮箱（可选，用于登录和通知）"),
        sa.Column("is_active", sa.Boolean(), nullable=False, comment="账户是否激活"),
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False, comment="主键 UUID"),
        sa.Column("created_at", sa.DateTime(), nullable=False, comment="创建时间"),
        sa.Column("updated_at", sa.DateTime(), nullable=False, comment="更新时间"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("username"),
    )
    op.create_index("idx_admin_user_email", "admin_user", ["email"], unique=True)
    op.create_index("idx_admin_user_is_active", "admin_user", ["is_active"], unique=False)
    op.create_index("idx_admin_user_username", "admin_user", ["username"], unique=True)
    op.alter_column(
        "merchant_application",
        "business_categories",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        comment='经营类目（JSON 数组，如 ["食品", "服装"]）',
        existing_comment='经营类目（JSONB 数组，如 ["食品", "服装"]）',
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "merchant_application",
        "business_categories",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        comment='经营类目（JSONB 数组，如 ["食品", "服装"]）',
        existing_comment='经营类目（JSON 数组，如 ["食品", "服装"]）',
        existing_nullable=False,
    )
    op.drop_index("idx_admin_user_username", table_name="admin_user")
    op.drop_index("idx_admin_user_is_active", table_name="admin_user")
    op.drop_index("idx_admin_user_email", table_name="admin_user")
    op.drop_table("admin_user")
    # ### end Alembic commands ###
